#! /usr/bin/env zsh
#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Disable username in prompt
DEFAULT_USER="$(whoami)"

# Functions

# History Adjustments
SAVEHIST=100000
HIST_IGNORE_SPACE="YES"
alias exit=" exit"
alias clear=" clear"

# Rbenv initialization
if [[ -d "$HOME/.rbenv" ]]; then
  export PATH="$HOME/.rbenv/bin:$PATH"
  eval "$(rbenv init -)"
fi

# tmux aliases
if (( $+commands[tmux] )); then
  function ttmux () {
    if (( ${+TMUX} )); then
      echo "Don't nest tmux sessions with this exec method."
      return
    fi
    exec "tmux" "new-session" "-A" "-s" "tmux"
  }

  function codemux () {
    if (( ${+TMUX} )); then
      echo "Don't nest tmux sessions with this exec method."
      return
    fi
    local dir="$(basename "$(pwd)" | sed "s/[^[:alpha:]^[:digit:]]//g")"
    exec "tmux" "new-session" "-A" "-s" "code-$dir"
  }
fi

# time aliases
alias 8601="date -u +\"%FT%TZ\""

function chpwd() {
    print -Pn "\e]2;%d\007"
    ls
}

[[ -f "${HOME}/.sdkman/bin/sdkman-init.sh" ]] && source "${HOME}/.sdkman/bin/sdkman-init.sh"
